In [4]:
import math

In [3]:
# Есть массив
arr = [1,2,3,4,5,6,7,8,9]

# Разделить его на 2 так
# 1 3 5 7 9
# 2 4 6 8

In [4]:
arr = [ 4, 5, 3, 2, 6, 7, 2, 5 ]
# Найти сумму всех элементов больше 4
# Т.е. тут 23

In [5]:
# Вывести все числа меньше 100, которые делятся на 3 в обратном порядке
# 99, 96, 93 ... 3

In [8]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Преобразовать его в 2х мерный:
#[[1, 2, 3],
# [4, 5, 6],
# [7, 8, 9]]

In [13]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]

# Поменять местами каждые 2 элемента
# arr = 2, 1, 4, 3, 6, 5, 8, 7
# Усложнение, чтобы рабоатло с нечетным числом элементов так
# arr = 2, 1, 4, 3, 6, 5, 8, 7, 9

In [9]:
# array intersection
arr1 = [5, 2, 4, 4 ]
arr2 = [1, 5, 4, 3 ]

# Найти пересечение массивов
# 5, 4
# Использовать Map или Set


In [10]:
arr1 = [5, 2, 4, 4]
arr2 = [1, 5, 4, 3]

# Найти Уникальные элементы массивов
# 1, 2, 3

In [ ]:
# Есть класс "Кошка", в данных класса есть число лап (paw) и длинна хвоста (tail), а еще функция describe(), которая пишет параметры кошки
class Cat:
    def describe(self):
        """Method describes cat's parameters:"""
        print(f"Mew! paw={self.paw} tail={self.tail}")

    def __init__(self, paw=4, tail=10):
        self.paw = paw
        self.tail = tail

# Т.е. кошек можно создавать таким образом
barsik = Cat(1, 2)
barsik.describe()

matros = Cat()
matros.describe()

In [22]:
# Есть 2 массива чисел:
paws = [1, 2, 3, 9]
tails = [5, 6, 7, 9]

# Создать массив кошек (Cats) куда слить вместе 2 массива
# cats[0].Paw == 1, cats[0].Tail=5
# cats[1].Paw == 2, cats[1].Tail=6

# Несколько примеров выполнения
# 1
cats = []
for i in range(len(paws)):          # Цикл по индексу массива
    cat = Cat(paws[i], tails[i])    # Создаем новую кошку
    cats.append(cat)                # Суем ее в мешок

# 2 (ОБЪЯСНИТЬ!)
cats = []
for paw, tale in zip(paws, tails):
    cats.append(Cat(paw, tale))

# 3 (ОБЪЯСНИТЬ!)
cats = [Cat(paw, tale) for paw, tale in zip(paws, tails)]

Mew paw=1 tail=5
Mew paw=2 tail=6
Mew paw=3 tail=7
Mew paw=9 tail=9


In [7]:
# Теперь наоборот задача. Есть массив кошек,
cats = []
cats.append(Cat(paw=1, tail=5))
cats.append(Cat(paw=2, tail=6))
cats.append(Cat(paw=3, tail=7))
cats.append(Cat(paw=4, tail=8))

# Наоборот получить
# paws = [1, 2, 3, 4 ]
# tails = [5, 6, 7, 8 ]

In [11]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Есть отсортированный массив, найти медиану
# Усложнение. Должно работать с
arr2 = [1, 2, 3, 4, 5, 6, 7, 8]

In [1]:
# Косынка!
# Есть такой массив обычных цифр
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

i = 0
# i < len(arr)

# Преобразовать его в массив массивов, так чтобы получилось так:
# [
# [1],
# [2, 3],
# [4, 5, 6],
# [7, 8, 9, 10],
# [11, 12, 13],    <- тут ожидалось бы 5 чисел, но столько в массиве не осталось, поэтому тут то, что осталось
# ]

# P.S. Должно работать с любым числом цифр
# P.P.S Распечатать этот массив массивов функцией print(), чтобы на экране выводилось как сверху

In [ ]:
# Слайдер
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 1. написать алгоритм, который берет первые n элементов маccива, вторые n и т.д.
# n=4
#  Короче, вот результат по нему понятно, что делается:
# [[1, 2, 3, 4],
#  [2, 3, 4, 5],
#  [3, 4, 5, 6],
#  ...
#  [6, 7, 8, 9]]

# 2. Написать функцию slide_arrays, которая возвращает такой результат для любого массива и n
# slide_arrays(arr, 4)
# Проверить, что:

arr2 = [9, 5, 2, 5, 9]

# slide_arrays(arr2, 4) выдаст
# [[9, 5, 2, 5], [5, 2, 5, 9]]
# slide_arrays(arr2, 10) выдаст
# [[9, 5, 2, 5, 9]]
# slide_arrays(arr2, 0) выдаст
# [[]]
# slide_arrays(arr2, -1) выдаст
# "heck you@!"

In [ ]:
arr = [1, 5, 2, 6, 3, 7, 0, 9, 8, 5, 2]

# Написать функцию cut_chunks(arr, n), которая разбивает массив на массивы по n элементов
# cut_chunks(arr, 4)
# Должно возвращать
# [[1, 5, 2, 6],
#  [3, 7, 0, 9]]
# Последние 3 цифры:
# 8, 5, 2 - остаток, который выкинут тк.к. их не было 4 штуки, не хватило
# Т.е. другими словами, эта функция должна корректно работать с массивами любого размера. Когда число элементов не укладывается в x*n - хвост отбрасывается.


In [16]:
# Задача на dict
names =   ["dog", "cat", "fox", "dog", "dog", "cat"]
values =  [ 5,     3,     2,     6,     4,     1   ]
# Найти сумму values для каждого слова.  "dog" = 15, "cat" = 4, "fox"= ...

In [17]:
arr = [5, 19, 13, 7, 1, 5, 13, 11, 3]
# Отсортировать массив (самостоятельно придумать какой-нибудь алгоритм)


In [18]:
names =  ["dog", "cat", "fox", "rat", "dog", "cat"]
values = [ 5,     3,     2,     6,     4,     1   ]
# Отсортировать имена в соответствии с цифрами в values
# {"cat", "fox", "cat", "dog", "dog", "rat"}

In [19]:
cats = []
cats.append(Cat(paw=9, tail=100))
cats.append(Cat(paw=2, tail=500))
cats.append(Cat(paw=2, tail=300))
cats.append(Cat(paw=4, tail=200))
cats.append(Cat(paw=7, tail=150))
cats.append(Cat(paw=1, tail=200))

# Отсортировать кошек по лапам
# Отсортировать кошек по хвостам
# Пользоваться чем угодно - встроенными функциями, stackoverflow

In [14]:
# Перемешать карты
# "Карта" - это число от 1 до 6, но оно может встречаться только по одному разу в колоде.
# Раздать карты случайным образом. Например
# [6, 5, 1, 2, 4, 3]
# т.е. в массиве каждое число может встречаться только один раз
# Нужно создать функцию, которая возвращает массив случайных чисел от 1 до 6, каждое из которых в этом массиве встречается только 1 раз.

In [15]:
# Есть набор каких-то чисел
arr = [5, 19, 13, 7, 1]
# Перемешать эти числа в случайном порядке

In [2]:
# Кодировка, раскодировка 
# Непонятное задание, но такая фигня везде используется в картинках, пикселах, байтстаффинг и т.д. 

# Есть 2-х мерный массив размером 3х3. В нем числа могут быть 0 и 1, например:
# [[0 1 0],
#  [1 0 1],
#  [0 0 1]]

# Например, AI и машин лернинге часто встречаются такие массивы где очень много нулей и мало единиц.
# Какой-нибудь пара гигов массив, в котором не нулей только 1.5% от общего числа элементов
# Мы хотим вместо того, чтобы таскать такой массив, использовать другой массив, который просто говорит,
# В каких местах изначального массива стоят единицы.

# А в этом массиве закодировано, где в массиве 3х3 стоят 1
arr = [1, 22, 10, 12]
            
# Каждое число в массиве arr, это где стоит 1 в массиве 3х3 
# по следующему правилу: 10*строка + столбец
# Например: 21 - строка индекс 2, колонка с индексом 1, т.е.
# [01, 22, 10, 12] означает, что 3х3 выглядит так:
# 0 1 0          потому что 1  - строка с индексом 0, колонка с индексом 1
# 1 0 1          потому что 10 и 12 - строка с индексом 1, колонки с индексом 0 и 2
# 0 0 1          потому что 22 - строка с индексом 2, колонка с индексом 2
# Ну вот это надо программно записать
# Т.е. создать функцию encode_array(arr), которая если в нее запихнуть верхний массив
# encode_array([1, 22, 10, 12]) вернет массив из 0 и 1, как расписано выше

# P.S. Это задание на программирование, а не знание алгоритмов. Т.е. надо придумать, как выполнить задание питоном.

In [21]:
# А теперь наоброт. Есть массив 3x3
arr3x3 = [[0, 1, 0], 
          [1, 0, 1], 
          [0, 1, 0]]

# Преобразовать в массив, где 10*строка + столбец, т.е. должно получиться
# [1, 10, 12, 21]