In [4]:
import math

In [15]:
class Cat:
    def say_name(self):
        print(f"Mew paw={self.paw} tail={self.tail}")

    def __init__(self, paw=4, tail=10):
        self.paw = paw
        self.tail = tail

barsik = Cat(1, 2)
barsik.say_name()

matros = Cat()
matros.say_name()


Mew paw=1 tail=2
Mew paw=4 tail=10


In [3]:
# Есть массив
arr = [1,2,3,4,5,6,7,8,9]

# Разделить его на 2 так
# 1 3 5 7 9
# 2 4 6 8

In [4]:
arr = [ 4, 5, 3, 2, 6, 7, 2, 5 ]
# Найти сумму всех элементов больше 4
# Т.е. тут 23

In [5]:
# Вывести все числа меньше 100, которые делятся на 3 в обратном порядке
# 99, 96, 93 ... 3

In [22]:
paws = [1, 2, 3, 9]
tails = [5, 6, 7, 9]

# Создать массив кошек (Cats) куда слить вместе 2 массива
# cats[0].Paw == 1, cats[0].Tail=5
# cats[1].Paw == 2, cats[1].Tail=6

# 1
cats = []
for i in range(len(paws)):
    cats.append(Cat(paws[i], tails[i]))

# 2
cats = []
for paw, tale in zip(paws, tails):
    cats.append(Cat(paw, tale))

# 3
cats = [Cat(paw, tale) for paw, tale in zip(paws, tails)]

Mew paw=1 tail=5
Mew paw=2 tail=6
Mew paw=3 tail=7
Mew paw=9 tail=9


In [7]:
cats = []
cats.append(Cat(paw=1, tail=5))
cats.append(Cat(paw=2, tail=6))
cats.append(Cat(paw=3, tail=7))
cats.append(Cat(paw=4, tail=8))

# Наоборот получить
# paws = [1, 2, 3, 4 ]
# tails = [5, 6, 7, 8 ]

In [8]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Преобразовать его в 2х мерный:
#[[1, 2, 3],
# [4, 5, 6],
# [7, 8, 9]]

In [9]:
# array intersection
arr1 = [5, 2, 4, 4 ]
arr2 = [1, 5, 4, 3 ]
           
# Найти пересечение массивов
# 5, 4
# Использовать Map или Set


In [10]:
arr1 = [5, 2, 4, 4]
arr2 = [1, 5, 4, 3]

# Найти Уникальные элементы массивов
# 1, 2, 3

In [11]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Есть отсортированный массив, найти медиану
# Усложнение. Должно работать с
arr2 = [1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
# Косынка!
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

i = 0
# i < len(arr)


# Преобразовать его в массив массивов:
# [1]
# [2, 3]
# [4, 5, 6]
# [7, 8, 9, 10]
# [11, 12, 13]    <- тут что осталось

SyntaxError: invalid syntax (Temp/ipykernel_25516/4013859609.py, line 6)

In [13]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]

# Поменять местами каждые 2 элемента
# arr = 2, 1, 4, 3, 6, 5, 8, 7
# Усложнение, чтобы рабоатло с нечетным числом элементов так
# arr = 2, 1, 4, 3, 6, 5, 8, 7, 9

In [14]:
# Перемешать карты
# "Карта" - это число от 1 до 6, но оно по одному разу в колоде
# Раздать карты случайным образом. Например 
# [6, 5, 1, 2, 4, 3]
# т.е. в массиве каждое число может встречаться только один раз

In [15]:
arr = [5, 19, 13, 7, 1]
# Перемешать эти числа в случайном порядке

In [16]:
names =   ["dog", "cat", "fox", "dog", "dog", "cat"]
values =  [ 5,     3,     2,     6,     4,     1   ]
# Найти сумму values для каждого слова "dog" = 15, "cat" = 4, "fox"= ...

In [17]:
arr = [5, 19, 13, 7, 1, 5, 13, 11, 3]
# Отсортировать массив (самостоятельно придумать какой-нибудь алгоритм)


In [18]:
names =  ["dog", "cat", "fox", "rat", "dog", "cat"]
values = [ 5,     3,     2,     6,     4,     1   ]
# Отсортировать имена в соответствии с цифрами в values
# {"cat", "fox", "cat", "dog", "dog", "rat"}

In [19]:
cats = []
cats.append(Cat(paw=9, tail=100))
cats.append(Cat(paw=2, tail=500))
cats.append(Cat(paw=2, tail=300))
cats.append(Cat(paw=4, tail=200))
cats.append(Cat(paw=7, tail=150))
cats.append(Cat(paw=1, tail=200))

# Отсортировать кошек по лапам
# Отсортировать кошек по хвостам
# Пользоваться чем угодно - встроенными функциями, stackoverflow

In [20]:
# Кодировка, раскодировка 
# Непонятное задание, но такая фигня везде используется в картинках, пикселах, байтстаффинг и т.д. 

# Есть 2-х мерный массив размером 3х3. В нем числа могут быть 0 и 1, например:
# [[0 0 1],
#  [1 0 0],
#  [0 0 1]]

# А в этом массиве закодировано, где в массиве 3х3 стоят 1
arr = [1, 22, 10, 12]
            
# Каждое число в массиве arr, это где стоит 1 в массиве 3х3 
# по следующему правилу: 10*строка + столбец
# Например: 21 - строка индекс 2, колонка с индексом 1, т.е.
# [1, 22, 10, 12] означает, что 3х3 выглядит так:
# 0 1 0          потому что 1  - строка с индексом 0, колонка с индексом 1
# 1 0 1          потому что 10 и 12 - строка с индексом 1, колонки с индексом 0 и 2
# 0 0 1          потому что 22 - строка с индексом 2, колонка с индексом 2
# Ну вот это надо программно записать

In [21]:
# А теперь наоброт. Есть массив 3x3
arr3x3 = [[0, 1, 0], 
          [1, 0, 1], 
          [0, 1, 0]]

# Преобразовать в массив, где 10*строка + столбец, т.е. должно получиться
# [1, 10, 12, 21]